[alias]
esp32c3 = "run --release --features=esp32c3 --target=riscv32imc-unknown-none-elf"
#esp32c6 = "run --release --features=esp32c6 --target=riscv32imac-unknown-none-elf"


[target.'cfg(target_arch = "riscv32")']
runner    = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
    "-C", "force-frame-pointers",
]

[env]
ESP_LOGLEVEL = "info"
SSID = "SSID"
PASSWORD = "PASSWORD"
STATIC_IP = "1.1.1.1 "
GATEWAY_IP = "1.1.1.1"
HOST_IP = "1.1.1.1"

[unstable]
build-std = ["alloc", "core"]